### ISSUE TITLE
Precompile Error: WARNING: eval into closed module Routing:

### ISSUE THREAD

**Issue by ueliwechsler** [wookay/Bukdu.jl#101]
After successfully creating a Julia webserver (similar to the rest example with the post `routes`) with this great package, I tried to precompile my code within a module. 

But the precompilation failed with this error message:
```julia
WARNING: eval into closed module Routing:
Expr(:call, :route, Expr(:::, Expr(:curly, :Val, Expr(:call, :Symbol, "POST"))), Expr(:::, Expr(:curly, :Val, Expr(:call, :Symbol, Base.SubString{String}(string="dyson/loadportfolio", offset=0, ncodeunits=5)))), Expr(:::, Expr(:curly, :Val, Expr(:call, :Symbol, Base.SubString{String}(string="dyson/loadportfolio", offset=6, ncodeunits=13))))) = Expr(:block, #= Symbol("C:\Users\UELIWECH\.julia\packages\Bukdu\YIeiP\src\Routing.jl"):58 =#, Expr(:call, :Route, DJSON.MicroServices.MicroServiceController, typeof(DJSON.MicroServices.load_portfolio_service)(), Base.Dict{Symbol, DataType}(slots=Array{UInt8, (16,)}[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00], keys=Array{Symbol, (16,)}[#<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>], vals=Array{DataType, (16,)}[#<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>], ndel=0, count=0, age=0x0000000000000000, idxfloor=1, maxprobe=0), Expr(:call, Expr(:curly, :Vector, Expr(:curly, :Pair, :String, :Any))), Array{Any, (0,)}[]))
  ** incremental compilation may be fatally broken for this module **
```
I assume that it has to do with the scope of `@eval`. Possibly here:
https://github.com/wookay/Bukdu.jl/blob/4e66675ab9ebfe1416202b3905ceff99643ecd57/src/Routing.jl#L58

I will have a closer look over the weekend. But if you already have any idea how to fix this, help would be much appreciated. I can also provide my source code if this error cannot be reproduced.

**Comment by wookay** [comment]
make a function for routes and pass that function to the `routes`.

https://github.com/wookay/TestBukdu.jl/blob/issue101/src/TestBukdu.jl
```julia
module TestBukdu

export custom_routes

# ...

function custom_routes()
    post("/loadportfolio", MicroServiceController, load_portfolio_service)
end

end
```

https://github.com/wookay/TestBukdu.jl/blob/issue101/test/testbukdu/run.jl
```julia
using TestBukdu # custom_routes
using Bukdu # routes

routes(custom_routes)
Bukdu.start(8080)
```

**Comment by ueliwechsler** [comment]
Thank you for your help! Precompilation works now.

Does this mean, that the `routes` have to be defined in the `Main`-scope?

**Comment by wookay** [comment]
you can define a function `__init__()` in a module, then Julia will call `__init__()` immediately after the module is loaded.

from https://docs.julialang.org/en/v1/manual/modules/#Module-initialization-and-precompilation-1

```julia
module TestBukdu

function __init__()
    routes(custom_routes)
end

# ...

end
```

**Comment by ueliwechsler** [comment]
Cool, thanks for your help 😃 

Does this also work with the `PackagCompiler` package for creating apps (executables)?
I tried to make your `apps` example 
https://github.com/wookay/Bukdu.jl/tree/master/examples/app
work with the new version of  `PackageCompiler` and `Julia v.1.4.2` on a Windows computer, but I couldn't make it work.

**Comment by wookay** [comment]
that example is out-dated. try 
https://julialang.github.io/PackageCompiler.jl/dev/sysimages/

**Comment by ueliwechsler** [comment]
I see. I somehow mixed the code for the old and the new `PackageCompiler` version. But I could make it work. I will make a PR to fix the app example.
