### ISSUE TITLE
Parse multi-part response

### ISSUE THREAD

**Issue by NiharikaPatel** [wookay/Bukdu.jl#107]
I am sending a json and a binary or text file and I need to Parse the response.body to just get the contents of it. Right now the request body looks like this 

```
-----------------------------211044896921589655921082427940
Content-Disposition: form-data; name="file"; filename="hw.txt"
Content-Type: text/plain

Hello World

-----------------------------211044896921589655921082427940
Content-Disposition: form-data; name="document"; filename="blob"
Content-Type: application/json

[object Object],[object Object],[object Object],[object Object]
-----------------------------211044896921589655921082427940--
```
How do i extract just the "Hello World" part without 
-----------------------------211044896921589655921082427940
Content-Disposition: form-data; name="file"; filename="hw.txt"
Content-Type: text/plain

**Comment by wookay** [comment]
related https://github.com/wookay/Bukdu.jl/blob/master/src/plugs/ContentParsers.jl

```julia
using Bukdu.Plug.ContentParsers: FormScanner, scan

reqbody = """
-----------------------------211044896921589655921082427940
Content-Disposition: form-data; name="file"; filename="hw.txt"
Content-Type: text/plain

Hello World

-----------------------------211044896921589655921082427940
Content-Disposition: form-data; name="document"; filename="blob"
Content-Type: application/json

[object Object],[object Object],[object Object],[object Object]
-----------------------------211044896921589655921082427940--
"""

scanner = FormScanner(Vector{UInt8}(reqbody), "-----------------------------211044896921589655921082427940")
body_params = scan(scanner)
@info :data String(read(body_params[1][2].data))
```

**Comment by NiharikaPatel** [comment]
Great! thank you, however, the `"-----------------------------211044896921589655921082427940"` changes every time. Is there a generalized way of finding the separator before feeding it in the FormScanner ?

**Comment by wookay** [comment]
see https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by NiharikaPatel** [comment]
Thanks! The json part is still as [object, Object]

**Comment by NiharikaPatel** [comment]
Figured it out, I was sending the json as an object instead of a string from the front end. Thanks for your help!
