### ISSUE TITLE
at parameter of the Static plug is not working.

### ISSUE THREAD

**Issue by bicycle1885** [wookay/Bukdu.jl#19]
Hi,

I'm trying to use Bukdu.jl to create a backend of [JBrowse](http://jbrowse.org/). However, the `at` parameter of the `Static` plug seems to be not working.

My code looks like this:

``` julia
Endpoint() do
    plug(Plug.Logger)
    plug(Plug.Static, at="/", from=jbrowse_directory)
    plug(Plug.Static, at="/data", from=normpath(jbrowse_directory, "sample_data", "json", "volvox"))
    plug(Router)
end
```

where `jbrowse_directory` is a path pointing to the install directory.

Looking the definition of `plug` for `Static`, the `at` parameter doesn't seem to be used in its definition: https://github.com/wookay/Bukdu.jl/blob/4f458308cf1fedb2ea54232ba74cb9ea7f4b739d/src/plug/static.jl#L45.

Is this a bug or an intended behavior?

**Comment by wookay** [comment]
hello, Kenta.
thanks for the issue!

**Comment by bicycle1885** [comment]
Thank you!
