### ISSUE TITLE
Parameter encoding too picky

### ISSUE THREAD

**Issue by pinx** [wookay/Bukdu.jl#36]
Bukdu does not accept parameters offered in www-form, i.e. spaces become "+"
http://elixir-lang.org/docs/stable/elixir/URI.html#encode_www_form/1
It *does* accept parameters in percent escaping:
http://elixir-lang.org/docs/stable/elixir/URI.html#encode/2
Elixir's Httpoison does the x-www-form-urlencoded, so Elixir and Bukdu are not compatible in this respect.

**Comment by wookay** [comment]
merged it to the master. thanks.
