### ISSUE TITLE
Live reload for local website testing

### ISSUE THREAD

**Issue by tlienart** [wookay/Bukdu.jl#47]
Hello, you kindly helped me on discourse to use `Bukdu` in order to serve a directory as a static website on `localhost:8000` with (on Julia 0.6.3):

```julia
using Bukdu
Endpoint() do
    plug(Plug.Static, at="/", from=normpath("."))
end
Bukdu.start(8000)
```

this works fine however I noted that it does not "live-reload" (i.e. if one of the files in `.` such as `index.html` gets modified, you need to manually refresh the browser to see the update). 

The [browser-sync](https://github.com/Browsersync/browser-sync) package in Javascript is quite useful for this. Can Bukdu do this too? From Julia Slack it seems that using WebSocket may be the solution for live-reload but I'm new to the web-app side of Julia and don't really know how to proceed. 

Thanks!

**Comment by wookay** [comment]
Hello, Thibaut Lienart. thanks for the feedback!
live reload is quite easy by reloading browser itself.

try this for another Julia 0.7 REPL.
https://github.com/wookay/Bukdu.jl/tree/sevenstars/examples/live-reload
(required Mac, Chrome browser, Julia 0.7 REPL)

in `watcher.jl`
```julia
using FileWatching

dir = "."
fm = FolderMonitor(dir)

function reload_chrome()
   run(`osascript chrome.scpt`)
end

watching_files = ["test.css"]

loop = Task() do
    while fm.open
        (fname, events) = wait(fm)::Pair
        println("fname ", fname)
        fname in watching_files && reload_chrome()
    end
end
schedule(loop)
```

I don't have the idea how `reload_chrome` works for other OS (windows, linux).

**Comment by tlienart** [comment]
Very nice, thanks! (and a nice example of `FileWatching` which I'm also trying to use). I guess I was originally hoping for a full-julia solution; Eric on Julia Slack webapp seemed to say that reloads could be done via WebSockets but I'm not exactly sure how that would be done.
Your solution is a nice simple workaround though, as far as I'm concerned it closes the issue :)
