### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by devnacho** [wookay/Bukdu.jl#54]
Hi @wookay thanks for this library 👏 😄 

Is there a way to set response headers like:
```
res.headers["Access-Control-Allow-Origin"] = "*"
```

I'm creating an API and I'm having problems with CORS.

Thanks!!!

**Comment by wookay** [comment]
Hi, just added examples in
https://github.com/wookay/Bukdu.jl/tree/master/examples/cors

thanks.

**Comment by devnacho** [comment]
You rock, thank you very much!!

**Comment by devnacho** [comment]
Hi @wookay. One additional question. 

How would you handle CORS preflight requests? (OPTION)

Thanks!

**Comment by wookay** [comment]
I have added the `OPTIONS` to the `master` branch.
see `using Bukdu: options` in https://github.com/wookay/Bukdu.jl/blob/master/test/bukdu/options.jl

However, things for the http stream with the header `Connection: Keep-Alive`,
the current implementation in Bukdu has very clumsy.
It also needs better test scenarios.

**Comment by devnacho** [comment]
@wookay I've updated your package to 0.3.4 but I'm getting an error
```
› /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia Server.jl
ERROR: LoadError: UndefVarError: options not defined
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1044
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] exec_options(::Base.JLOptions) at ./client.jl:231
 [5] _start() at ./client.jl:425
in expression starting at /Users/nachogutierrez/Projects/timeline-calc/Server.jl:8
```

Is it possible that `options` needs to be exported here?
https://github.com/wookay/Bukdu.jl/blob/ef439b358e10b0db133d8fce0b2d74230b3bc041/src/routes.jl#L5

Thanks!

**Comment by wookay** [comment]
you should `using Bukdu: options` explicitly. I don't think that it should be export the `options` by default.

**Comment by devnacho** [comment]
Ahaha I tried that but for some reason I still get the error. I'll continue investigating

**Comment by devnacho** [comment]
It should work but I get this error

<img width="532" alt="imagen" src="https://user-images.githubusercontent.com/623766/50157930-77917880-02b1-11e9-95c3-73362e7a56a4.png">

`using Bukdu: get` works

**Comment by wookay** [comment]
`options` has not yet tagged into the official METADATA repository. please pull the `master` branch.
```
using Pkg
pkg"add Bukdu#master"
```
