### ISSUE TITLE
Bukdu.jl/examples/rest/ex3.jl -- options not defined

### ISSUE THREAD

**Issue by NiharikaPatel** [wookay/Bukdu.jl#55]
On running Bukdu.jl/examples/rest/ex3.jl  im getting the following error message

*ERROR: LoadError: UndefVarError: options not defined
Stacktrace:
 [1] (::getfield(Main, Symbol("##3#4")))() at /web_serverX.jl:32
 [2] routes(::getfield(Main, Symbol("##3#4"))) at /root/.julia/packages/Bukdu/kBTab/src/routes.jl:115
 [3] top-level scope at none:0
 [4] include at ./boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1038
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] exec_options(::Base.JLOptions) at ./client.jl:239
 [8] _start() at ./client.jl:432*

**Comment by wookay** [comment]
which version do you use?
lastest is Bukdu v0.4.1

**Comment by NiharikaPatel** [comment]
I’m using whatever is on master.

‘’’julia
Using Pkg,
Pkg.add(“Bukdu”)
‘’’
Do you suggest I clone and build a specific branch ?

**Comment by wookay** [comment]
just update your packages
```
julia> using Pkg

julia> Pkg.update()
```

**Comment by NiharikaPatel** [comment]
Is that version compatible with julia 0.7.0 ? Im not able to update beyond Bukdu version 0.3.4.

**Comment by wookay** [comment]
Bukdu requires Julia 1.0 since Bukdu v0.4.0

**Comment by NiharikaPatel** [comment]
Thank you, I upgraded to Julia 1.0.2 and the error seems to have gone. It runs locally but It does not seem to run on docker. It just exits after building the latest image.

**Comment by NiharikaPatel** [comment]
Step 34/37 : RUN julia -e "using Bukdu"
 ---> Using cache
 ---> 2b946cbd5fbb
Step 35/37 : RUN julia -e "using HTTP"
 ---> Using cache
 ---> 13531fa526d6
Step 36/37 : COPY ./deployment/web_serverX.jl .
 ---> Using cache
 ---> 60f9bb786bc7
Step 37/37 : CMD ["julia", "web_serverX.jl"]
 ---> Using cache
 ---> 857a6ffd38d0
Successfully built 857a6ffd38d0
Successfully tagged ctk-image:latest

>

**Comment by NiharikaPatel** [comment]
The issue on Docker seems to be because of 

`> CMD ["julia", "web_serverX.jl"]`

as opposed to 
`julia> include("web_serverX.jl")
`
The CMD statement does not get into the julia REPL

**Comment by wookay** [comment]
you should put `Base.JLOptions().isinteractive==0 && wait()` in the end of the program.

**Comment by NiharikaPatel** [comment]
Thank you, now it does not exit however, it still does not work on Docker. It says :
`Successfully built 744fec529793
Successfully tagged ctk-image:latest
INFO: Bukdu Listening on 127.0.0.1:8080
`
But the virtual machine does not really talk to my web app. I do not get an error message either. 
It does talk when I deploy the web server locally with julia though.

**Comment by NiharikaPatel** [comment]
Never mind! solved it with `Bukdu(8080,host="0.0.0.0") `the `Bukdu(8080,"0.0.0.0")` from issue 53 used to give me an error message because its an optional argument.
