### ISSUE TITLE
Handling Requests in Parallel?

### ISSUE THREAD

**Issue by haydenfree** [wookay/Bukdu.jl#66]
If I set up a simple RESTController and expose some functions of a package to be used as a web API, will Bukdu handle requests in parallel? Some functions may take several seconds to complete.

Thank you!

**Comment by wookay** [comment]
see simple REST server
https://gist.github.com/wookay/0dd13a45bb878bfdffb6cf21acabcb95
try get multiple `short` requests during get the `long` request.

and see also to load test c10k with `nginx`
https://medium.com/@richardanaya/how-to-create-a-multi-threaded-http-server-in-julia-ca12dca09c35

**Comment by haydenfree** [comment]
It seems the requests can be handled in parallel. If/when I need to do more serious load testing I will refer to the article you've attached.

Thank you so much, your response was extremely helpful.
