### ISSUE TITLE
Mount folder to public

### ISSUE THREAD

**Issue by darrencl** [wookay/Bukdu.jl#78]
Hi, I try to look for a function to mount a specific folder to public in the documentation (which I think need to be improved with adding docstring and example of usage), but couldn't find it. 

What I mean by mount is equivalent `app.use()` in nodeJS. I'm just wondering if there's any way I can do that in `bukdu.jl`?

Thanks!

**Comment by darrencl** [comment]
Saw there's `plug` which seems to be what I'm looking for, I'll try that!

**Comment by wookay** [comment]
`plug` with `Plug.Static` https://github.com/wookay/Bukdu.jl/blob/master/test/bukdu/plugs/static.jl
it is originated from Phoenix's plug https://hexdocs.pm/plug/Plug.Static.html
