### ISSUE TITLE
Auth pipeline and redirect

### ISSUE THREAD

**Issue by lucianolorenti** [wookay/Bukdu.jl#79]
Hello. This is not an issue but a question. I want certain pages only to be accessed by authorized users. If a not logged user tries to access to a login required area I want to redirect him to the login page. I made something like this but it does not work. How is the correct way to do it?

```julia
struct Authorization <: Plug.AbstractPlug
end
function plug(::Type{Authorization}, conn::Conn)
    req = conn.request
    conn.params[:auth]  = user_authorized(conn)    
end

struct RedirectToLogin <: Plug.AbstractPlug
end
function plug(::Type{RedirectToLogin}, conn::Conn)
    if !conn.params[:auth]
        Bukdu.redirect_to(conn, "/login")
    end
end
pipeline(:auth) do conn::Conn
    plug(Authorization, conn)
    plug(RedirectToLogin, conn)
end

routes(:auth) do
    get("/authorized_zone", IndexController, authorized_index)
   
end
routes() do
    get("/login", IndexController, login)
end
```

**Comment by wookay** [comment]
hi. I added the `private` field to the `Conn` (5cc71c79db1f0845c584e581c885b137e82f554b)  at `master` branch.
please don't use the `conn.params` as to store the auth info.

the `redirect_to` function should be used like this
```julia
function authorized(conn::Conn)::Bool
    get(conn.private, :auth, false)
end

function index(c::IndexController)
    !authorized(c.conn) && return redirect_to(c.conn, "/login")
    render(Text, "index")
end
```

Example:
https://gist.github.com/wookay/fed24f2334d3be3524661b83f98fde30

thanks.

**Comment by lucianolorenti** [comment]
Thank you very much! Now it is working
